config/routes.rb
Rails.application.routes.draw do

	devise_for :users
	resources :charges

	root 'home#index'

	get '/cart', to: 'carts#cart', as: 'cart'

	# do not touch this line !!!
	get 'carts/create/:id', to:'carts#create', as: 'add_to_cart'
	delete 'carts/create/id', to: 'carts#destroy', as: 'remove_from_cart'
	# post 'charges/new', to: 'charges#new', as: 'new_charge'
	# ==========================

	get '/items/all', to: 'items#listing'
	get '/home/index'

	get '/single/:id', to: 'home#single', as: 'single'
	get '/product', to: 'home#product', as: 'product'
	get '/about', to: 'home#about'
	get '/contact', to: 'home#contact'
	get '/services', to: 'home#services'
	get '/account', to: 'home#account'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :item
	belongs_to :user
	has_many :items
 end

app/models/item.rb
class Item < ApplicationRecord
	has_many :carts
	has_many :users, through: :carts
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

	has_many :carts
	has_many :items, {:through=>:carts, :source=>"item"}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception
	before_action :set_cart

	private
		def set_cart
			@cart = Cart.find(session[:cart_id])
		rescue ActiveRecord::RecordNotFound
			@cart = Cart.create
			session[:cart_id] = @cart.id
		end
	before_action :sanitize_devise_params, if: :devise_controller?

		def sanitize_devise_params
			devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
		end

end

app/controllers/cart_controller.rb
class CartsController < ApplicationController


  before_action :set_cart, only: [:create][:destroy]
  before_action :set_cart_only, only: [:destroy]


  def create
    @cart.add_item(params)

    if @cart.save
      redirect_to cart_path
    else
      flash[:error] = 'there was a problem adding this item to your cart'
      redirect_to @item
    end


    def destroy
      @cart_item.destroy
      redirect_to_carts_path
    end

    private


    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end


    def cart_item_params
      params.require(:carts_item).permit(:item_id, :cart_id, :quantity)
    end

  end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:create, :destroy]
  before_action :set_item, only: [:destroy]
  before_action :authenticate_user!

  def cart
    @user = current_user
    @carts = Cart.all
  end

  def new
  end

  def create
    @user = current_user
    new_item = add_product(@user, params)
    @cart = Cart.new(user: new_item[:user], item: new_item[:item]) 

      if @cart.save
        redirect_to root_path
      else
        flash[:error] = 'There was a problem adding this item to your cart.'
        redirect_to @product
  end
end
  def destroy
    @user = current_user
    @cart = Cart.where(user: @user).where(item: @item)
    @cart.destroy_all
    redirect_to cart_path
  end

  private

  def set_item
    @item = Item.find(params[:format].to_i)
  end

  def item_params
    params.require(:item).permit(:id, :cart_id, :quantity)
  end

  def add_product(current_user, product_params)
      current_item = Item.find_by(id: product_params[:id])

      new_item = {user: current_user, item: current_item}
   end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	before_action :authenticate_user!, except: [:show]

	def new
		@user = current_user
		@cart = Cart.where(user: @user)
		# @date = Time.new
		@total_price = 24.0
		@cart.each do |c|
			@total_price += c.item.price
			# Order.create(user: @user, item: c.item, date: @date)
			# c.destroy_all
		end
	end

	def create
		@user = current_user
		@cart = Cart.where(user: @user)
		@date = Time.new
		@total_price = 24.0
		@cart.each do |c|
			@total_price += c.item.price
			Order.create(user: @user, item: c.item, date: @date)
			c.destroy
		end

	  # Amount in cents
	  puts "===================="
	  puts
	  puts
	  puts @user.email
	  puts
	  puts
	  puts "===================="
	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @total_price.to_i * 100,
	    :description => 'Order on Webshop-X',
	    :currency    => 'usd'
	  )
	  UserMailer.order_email(@amount, charge.currency, customer.email).deliver_now!
	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :single, :product, :services, :about, :contact]
  def index
  	@items = Item.all
  end
  def account
    @arr = []
    @orders = Order.where(user: current_user)
    @orders.each do |o|
      @arr << o.date
    end
    @arr.uniq
  end
  def single
  	@item = Item.find_by(id: params[:id])
  end

  def product
   	@items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def listing
  	@items = Item.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/cart/cart.html.erb
<h1>Carts#show</h1>

app/views/carts/cart.html.erb
<div class="formu">
  <div class="formu-text">
		<h1>Your cart:</h1>
<div class="global-cart">
		<span style="display: none;"><%= var = 0 %></span>
		<% @user.items.each do |item| %>
			<div id="items-added">
				<ul>
          <div class="cart_data">
            <li><%= image_tag item.image_url, :class=>"image_resize" %></li>
          </div>
          <div class="cart_data">
      			<li><%= item.title %></li>
          </div>
          <div class="cart_data">
          	<li><%= item.description %></li>
          </div>
          <div class="cart_data">
			      <span style="display: none;"><%= var += item.price %></span>
          </div>
			      <li><%= item.price %>€</li>
		    	<%= button_to "Remove", remove_from_cart_path(Cart.find_by(item: item).item.id), data: { confirm: "Are you sure?" }, method: :delete, :class=>"btn btn-primary btn-outline btn-lg"  %>
		    </ul>
    	</div>
    <% end %>
<br/>

<div id="total">
    <div class="cart_btn_bot">
	<ul>
		<li>Subtotal <%= var %>€</li>
		<li>Shipping : <%= ship = 24.0 %>€</li>
		<li>Total <%= var + ship %>€</li>

		<button class= "btn btn-primary btn-outline btn-lg" ><%= link_to "Place Your Order", new_charge_path %></button>
	</ul>
</div>
		</div>
	</div>
</div>
</div>

app/views/charges/charges.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/charges/create.html.erb
<div class="formu">
  <div class="formu-text">
    <h2>Thanks, you paid <strong>$<%= @total_price %></strong>!</h2>
  </div>
</div>

app/views/charges/new.html.erb
<div class="formu">
  <div class="formu-text">
    <%= form_tag charges_path do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
        <label class="amount">
          <span>Amount: $<%= @total_price %></span>
        </label>
      </article>
    <div class="btn-stripe">
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="A month's subscription"
              data-amount=<%= @total_price.to_i * 100 %>
              data-locale="auto"></script>
    <% end %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<%= render 'renders/item-banner' %>
<%= render 'renders/about' %>

app/views/home/account.html.erb
<div class="text-account">
	<h4>Welcome to your account. You're logged in with the following email : <strong><%= current_user.email %></strong>. </h4>
	<h2>Here is your recent orders :</h2>

	<ul>
		<% @arr.each do |date| %>
			<span style="display: none;"><%= var = 24.0 %></span>
			<li>You've placed the order N°<%= Order.find_by(date: date).id %> at <%= date %></li>
			<ul>
				<% Order.where(date: date).each do |order| %>
					<span style="display: none;"><%= var += order.item.price%></span>
					<li><%= order.item.title %> : <%= order.item.price %></li>
				<% end %>
				<li>Plus $24.0 for shippement</li>
				<li> <strong>Total : $<%= var %></strong> </li>
			</ul>
			<br>
		<% end %>
	</ul>

</div>

app/views/home/contact.html.erb
<%= render 'renders/contact-banner' %>
<div id="fh5co-contact">
	<div class="container">
		<div class="row">
			<div class="col-md-5 col-md-push-1 animate-box">

				<div class="fh5co-contact-info">
					<h3>Contact Information</h3>
					<ul>
						<li class="address">198 West 21th Street, <br> New York NY 10016</li>
						<li class="phone"><a href="tel://1234567920">+ 1234 5678 90</a></li>
						<li class="email"><a href="mailto:info@yoursite.com">contact.thp.paris@gmail.com</a>
						<li class="url"><a href="https://webshop-x.herokuapp.com/">Here you already are!</a></li>
					</ul>
				</div>

			</div>
			<div class="col-md-6 animate-box">
				<h3>Get In Touch</h3>
				<form action="#">
					<div class="row form-group">
						<div class="col-md-6">
							<!-- <label for="fname">First Name</label> -->
							<input type="text" id="fname" class="form-control" placeholder="Your firstname">
						</div>
						<div class="col-md-6">
							<!-- <label for="lname">Last Name</label> -->
							<input type="text" id="lname" class="form-control" placeholder="Your lastname">
						</div>
					</div>

					<div class="row form-group">
						<div class="col-md-12">
							<!-- <label for="email">Email</label> -->
							<input type="text" id="email" class="form-control" placeholder="Your email address">
						</div>
					</div>

					<div class="row form-group">
						<div class="col-md-12">
							<!-- <label for="subject">Subject</label> -->
							<input type="text" id="subject" class="form-control" placeholder="Your subject of this message">
						</div>
					</div>

					<div class="row form-group">
						<div class="col-md-12">
							<!-- <label for="message">Message</label> -->
							<textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Say something about us"></textarea>
						</div>
					</div>
					<div class="form-group">
						<input type="submit" value="Send Message" class="btn btn-primary">
					</div>

				</form>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<%= render "renders/main-slider" %>
<%= render "renders/authenticity-banner" %>
<%= render "renders/item-grid" %>
<%= render "renders/testimony" %>

app/views/home/product.html.erb
<%= render 'renders/sneakers-banner' %>
<%= render "renders/item-grid" %>

app/views/home/services.html.erb
<%= render 'renders/services-banner' %>
<div id="fh5co-services" class="fh5co-bg-section">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-sm-4 text-center">
				<div class="feature-center animate-box" data-animate-effect="fadeIn">
					<span class="icon">
						<i class="icon-credit-card"></i>
					</span>
					<h3>Credit Card</h3>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove</p>
					<p><a href="#" class="btn btn-primary btn-outline">Learn More</a></p>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 text-center">
				<div class="feature-center animate-box" data-animate-effect="fadeIn">
					<span class="icon">
						<i class="icon-wallet"></i>
					</span>
					<h3>Save Money</h3>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove</p>
					<p><a href="#" class="btn btn-primary btn-outline">Learn More</a></p>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 text-center">
				<div class="feature-center animate-box" data-animate-effect="fadeIn">
					<span class="icon">
						<i class="icon-paper-plane"></i>
					</span>
					<h3>Free Delivery</h3>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove</p>
					<p><a href="#" class="btn btn-primary btn-outline">Learn More</a></p>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 text-center">
				<div class="feature-center animate-box" data-animate-effect="fadeIn">
					<span class="icon">
						<i class="icon-calendar"></i>
					</span>
					<h3>Lifetime Warranty</h3>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove</p>
					<p><a href="#" class="btn btn-primary btn-outline">Learn More</a></p>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 text-center">
				<div class="feature-center animate-box" data-animate-effect="fadeIn">
					<span class="icon">
						<i class="icon-clapperboard"></i>
					</span>
					<h3>Branded Model</h3>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove</p>
					<p><a href="#" class="btn btn-primary btn-outline">Learn More</a></p>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 text-center">
				<div class="feature-center animate-box" data-animate-effect="fadeIn">
					<span class="icon">
						<i class="icon-drive"></i>
					</span>
					<h3>Affordable</h3>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove</p>
					<p><a href="#" class="btn btn-primary btn-outline">Learn More</a></p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/single.html.erb
<!-- %= render "renders/item-pic-btn" %-->
<div class="row">
  <div class="col-md-10 col-md-offset-1 animate-box">
    <div class="img-preview">
      <%= image_tag( @item.image_url ) %>
    </div>
    <div class="row animate-box">
      <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
        <h2><%= @item.title %></h2>
        <p>
          <a href=<%= add_to_cart_path(@item.id) %> class="btn btn-primary btn-outline btn-lg">Add to Cart</a>

        </p>
      </div>
    </div>
  </div>
</div>

<!-- render "renders/item-preview" -->
<div id="fh5co-product">
	<div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="fh5co-tabs animate-box">
          <ul class="fh5co-tab-nav">
            <li class="active"><a href="#" data-tab="1"><span class="icon visible-xs"><i class="icon-file"></i></span><span class="hidden-xs">Product Details</span></a></li>
            <li><a href="#" data-tab="2"><span class="icon visible-xs"><i class="icon-bar-graph"></i></span><span class="hidden-xs">Specification</span></a></li>
            <li><a href="#" data-tab="3"><span class="icon visible-xs"><i class="icon-star"></i></span><span class="hidden-xs">Feedback &amp; Ratings</span></a></li>
          </ul>

          <!-- Tabs -->
          <%= render "renders/tabs/product-details" %>
          <%= render "renders/tabs/product-specification" %>
          <%= render "renders/tabs/product-feedbacks" %>
            
        </div>
      </div>
    </div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SHOP.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<title>Shop &mdash; Free Website Template, Free HTML5 Template by gettemplates.co</title>
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta name="description" content="Free HTML5 Website Template by gettemplates.co" />
  	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
  	<meta name="author" content="gettemplates.co" />
  	<meta property="og:title" content=""/>
  	<meta property="og:image" content=""/>
  	<meta property="og:url" content=""/>
  	<meta property="og:site_name" content=""/>
  	<meta property="og:description" content=""/>
  	<meta name="twitter:title" content="" />
  	<meta name="twitter:image" content="" />
  	<meta name="twitter:url" content="" />
  	<meta name="twitter:card" content="" />
  	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

  	<!-- Modernizr JS -->
  	<!-- <script src="assets/js/modernizr-2.6.2.min.js"></script> -->
    <%= javascript_include_tag "js/modernizr-2.6.2.min.js" %>
  </head>



  <body>
<%= render "renders/navbar"%>
<%= yield %>
<%= render "renders/newsletter" %>
<%= render "renders/footer"%>

    <!-- jQuery -->


    <!-- <script src="assets/js/jquery.min.js"></script> -->
    <%= javascript_include_tag "js/jquery.min.js" %>
    <!-- jQuery Easing -->
    <!-- <script src="assets/js/jquery.easing.1.3.js"></script> -->
    <%= javascript_include_tag "js/jquery.easing.1.3.js" %>
    <!-- Bootstrap -->
    <%= javascript_include_tag "js/bootstrap.min.js" %>
    <!-- <script src="assets/js/bootstrap.min.js"></script> -->
    <!-- Waypoints -->
    <%= javascript_include_tag "js/jquery.waypoints.min.js" %>
    <!-- <script src="assets/js/jquery.waypoints.min.js"></script> -->
    <!-- Carousel -->
    <%= javascript_include_tag "js/owl.carousel.min.js" %>
    <!-- <script src="assets/js/owl.carousel.min.js"></script> -->
    <!-- countTo -->
    <%= javascript_include_tag "js/jquery.countTo.js" %>
    <!-- <script src="assets/js/jquery.countTo.js"></script> -->
    <!-- Flexslider -->
    <%= javascript_include_tag "js/jquery.flexslider-min.js" %>
    <!-- <script src="assets/js/jquery.flexslider-min.js"></script> -->
    <!-- Main -->
    <%= javascript_include_tag "js/main.js" %>
    <!-- <script src="assets/js/main.js"></script> -->
  </body>
</html>

app/views/renders/_contact-banner.html.erb
<header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background: url(<%= asset_path 'brkln.jpg' %>) no-repeat; background-size: cover;">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <div class="display-t">
          <div class="display-tc animate-box" data-animate-effect="fadeIn">
            <h1>Contact</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/renders/_item-grid.html.erb
<div id="fh5co-product">
  <div class="container">
    <div class="row animate-box">
      <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
        <!-- <p>Here are the hottest and lastest releases.</p> -->
      </div>
    </div>

    <div class="row">
      <% @items.each do |item| %>
        <div class="col-md-4 text-center animate-box">
          <div class="product">
            <div class="product-grid" style="background: url(<%= asset_path item.image_url %>) no-repeat; background-size: cover;">
              <div class="inner">
                <p>
                  <a href= <%= add_to_cart_path(item.id) %> class="icon"><i class="fas fa-shopping-cart"></i></a>
                  <a href=<%= single_path(item.id) %> class="icon"><i class="fas fa-eye"></i></i></a>
                </p>
              </div>
            </div>
            <div class="desc">
              <h3><a href=<%= single_path(item.id) %>><%= item.title %></a></h3>
              <span class="price"><%= item.price %>$</span>
            </div>
          </div>  
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/renders/_main-slider.html.erb
<aside id="fh5co-hero" class="js-fullheight">
  <div class="flexslider js-fullheight">
    <ul class="slides">
      <li style="background: url(<%= asset_path 'jordan-1-sbb.jpg' %>) no-repeat; background-size: cover;">
        <div class="overlay-gradient"></div>
        <div class="container">
          <div class="col-md-6 col-md-offset-3 col-md-pull-3 js-fullheight slider-text">
            <div class="slider-text-inner">
              <div class="desc">
                <span class="price">$800</span>
                <h2>Air Jordan 1 Black Toe</h2>
                <p>Released in 2015, the “Shattered Backboard” Air Jordan 1 High is inspired by an exhibition game Michael Jordan participated in back in 1985 where he broke the glass backboard after a dunk.</p>
                <p><a href= <%= single_path(@items.find_by(title: 'Air Jordan 1 Black Toe').id) %> class="btn btn-primary btn-outline btn-lg">Purchase Now</a></p>
              </div>
            </div>
          </div>
        </div>
      </li>
      <li style="background: url(<%= asset_path 'off-white-unc.jpg' %>) no-repeat; background-size: cover;">
        <div class="container">
          <div class="col-md-6 col-md-offset-3 col-md-pull-3 js-fullheight slider-text">
            <div class="slider-text-inner">
              <div class="desc">
                <span class="price">$530</span>
                <h2>Off White Jordan 1 UNC</h2>
                <p>For his third edition of the monumental Off-White x Air Jordan 1, Virgil Abloh focused on the "UNC" colorway of Michael Jordan's first signature shoe.</p>
                <p><a href=<%= single_path(@items.find_by(title: 'Off White Jordan 1 UNC').id) %> class="btn btn-primary btn-outline btn-lg">Purchase Now</a></p>
              </div>
            </div>
          </div>
        </div>
      </li>
      <li style="background: url(<%= asset_path 'off-white-zoom-fly.jpg' %>) no-repeat; background-size: cover;">
        <div class="container">
          <div class="col-md-6 col-md-offset-3 col-md-pull-3 js-fullheight slider-text">
            <div class="slider-text-inner">
              <div class="desc">
                <span class="price">$750</span>
                <h2>Off White Zoom Fly</h2>
                <p>There’s was no missing the hyped OFF-WHITE x Nike “THE TEN” collection in 2017, but here is one of the most overlooked models in the set, the Zoom Fly.</p>
                <p><a href=<%= single_path(@items.find_by(title: 'Off White Zoom Fly').id) %> class="btn btn-primary btn-outline btn-lg">Purchase Now</a></p>
              </div>
            </div>
          </div>
        </div>
      </li>
      <li style="background: url(<%= asset_path 'pirate-black.jpg' %>) no-repeat; background-size: cover;">
        <div class="container">
          <div class="col-md-6 col-md-offset-3 col-md-pull-3 js-fullheight slider-text">
            <div class="slider-text-inner">
              <div class="desc">
                <span class="price">$540</span>
                <h2>Yeezy Boost 350 Pirate Black</h2>
                <p>Some would say the adidas Yeezy Boost 350 in "Pirate Black" is the most popular colorway of the most preferred silhouette from Kanye West's collaboration with Adidas.</p>
                <p><a href=<%= single_path(@items.find_by(title: 'Yeezy Boost 350 Pirate Black').id) %> class="btn btn-primary btn-outline btn-lg">Purchase Now</a></p>
              </div>
            </div>
          </div>
        </div>
      </li>
      </ul>
    </div>
</aside>

app/views/renders/_navbar.html.erb
<!-- Navbar -->
<div id="page">
<nav class="fh5co-nav" role="navigation">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-xs-2">
        <div id="fh5co-logo"><a href="/">Shop.</a></div>
      </div>
      <div class="col-md-6 col-xs-6 text-center menu-1">
        <ul>
          <li><a href="/product">Sneakers</a></li>
          <li><a href="/services">Services</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>
      </div>
      <div class="col-md-3 col-xs-4 text-right hidden-xs menu-2">
        <ul>
          <li class="has-dropdown">
            
            <%= link_to "User", account_path %>
            <ul class="dropdown">
              <% if user_signed_in? %>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <li><%= link_to "Edit account", edit_user_registration_path %></li>
              <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <% end %>
            </ul>
          </li>
            <% if user_signed_in? %>
              <li class="shopping-cart"><%= link_to simple_format('<span><small>'+current_user.items.count.to_s+'</small><i class="fas fa-shopping-cart"></i></span>'), cart_path(id: 'home'), class: 'cart' %>
            <% else %>
              <li class="shopping-cart"><%= link_to simple_format('<span><small>0</small><i class="fas fa-shopping-cart"></i></span>'), cart_path(id: 'home'), class: 'cart' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/renders/items/_air-jordan-1-black-toe.html.erb
<div class="col-md-4 text-center animate-box">
  <div class="product">
    <div class="product-grid" style="background: url(<%= asset_path 'jordan-1-black-toe.png' %>) no-repeat; background-size: cover;">
      <div class="inner">
        <p>
          <a href= <%= add_to_cart_path(15) %> class="icon"><i class="fas fa-shopping-cart"></i></a>
          <a href="single.html" class="icon"><i class="fas fa-eye"></i></i></a>
        </p>
      </div>
    </div>
    <div class="desc">
      <h3><a href="single.html">Air Jordan 1 Black Toe</a></h3>
      <span class="price">$100</span>
    </div>
  </div>
</div>